apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-cpu-memory-requests
  annotations:
    policies.kyverno.io/title: Require CPU and Memory Requests
    policies.kyverno.io/category: Best Practices / Rightsizing
    policies.kyverno.io/severity: medium
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: validate-requests-set
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "All containers must define both CPU and memory requests."
        pattern:
          spec:
            containers:
              - resources:
                  requests:
                    cpu: "?*"
                    memory: "?*"
